---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: docker-cluster
network.host: 0.0.0.0

http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: Authorization,Content-Type,X-Requested-with,Content-Length

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: basic
xpack.security.enabled: true
# xpack.http.proxy.host: '10.8.94.3'
# xpack.http.proxy.port: 3128

xpack.security.authc.token.enabled: true
xpack.security.authc.realms.saml.saml1:
  order: 2 
  attributes.principal: "http://schemas.goauthentik.io/2021/02/saml/username"
  attributes.groups: "http://schemas.xmlsoap.org/claims/Group" 
  idp.metadata.path: "saml/idp-metadata.xml" 
  idp.entity_id: "authentik" 
  sp.entity_id: "https://strat-elk.jqdomain.com/" 
  sp.acs: "https://strat-elk.jqdomain.com/api/security/saml/callback"
  sp.logout: "https://strat-elk.jqdomain.com/logout"