## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml

name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~

filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /data/**/*.csv
  tail_file: false
  clean_removed: true
  close_removed: true
  fields:
    hostname: strat020
    index: jian_csv

output.logstash:
  hosts: ["10.9.186.14:5044"]