## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml

name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~

filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /logs/**/*.log
  tail_file: ${TAIL_FILE}
  clean_removed: true
  close_removed: true
  fields:
    hostname: ${HOSTNAME}

output.logstash:
  hosts: ["${LOG_SERVER}"]