ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM harbor.jqdomain.com/personal-xin-zhu/elasticsearch:${ELASTIC_VERSION}

# COPY ./config /usr/share/elasticsearch/config
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu